### ISSUE TITLE
About collaborating this repo 

### ISSUE THREAD

**Issue by palindrom615** [Pony-House/New-Browser-Ponies#1]
Hi. I have been working on your repo for a few monthes. My main contribution is focused on modernizing js syntaxes. I have worked for maintainable code. anyway single 3.6k line `browserponies.js` file is hard to read ;)

My main goal is to make this repo stand-alone library and upload it into npm, so web developers can just put it in their site. Yet I have not achieved the goal.

You seems keep working on this repository. I'm impressed with your gh page repo. Your work seems nice!

it's waste of time and effort to maintain each of your and my own repo. so, I guess we can work along.

Is there any way to contact you about more detail? there's no such thing like dm in github... gitter or facebook messenger would be perfect.

**Comment by JasminDreasond** [comment]
my God. I'm sorry I didn't see this issue. In 2018 I was still new to Github in 2018. c':
Well, today you can currently contact me via my Discord server where you can directly chat with me via Discord DM.

If there is still a chance to talk about the project, feel free.
